version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg15
    container_name: bape_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=BAPE_BD
    ports:
      - "5432:5432"
    restart: always

  api:
    build: .
    container_name: bape_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=BAPE_BD
      - SECRET_KEY=changethis_to_a_secure_random_string
      - POSTGRES_HOST=db
      # Make sure the API knows how to reach the Baileys Engine (Service name)
      - BAILEYS_URL=http://baileys:3005
    depends_on:
      - db
    restart: always

  baileys:
    build: ./baileys_engine
    container_name: bape_baileys
    ports:
      - "3005:3005"
    volumes:
      - ./baileys_engine:/app
      - /app/node_modules # Prevents local node_modules from overriding container's
    environment:
      - PORT=3005
      # Make sure the Engine knows how to reach the API webhook (Service name)
      - WEBHOOK_URL=http://api:8000/webhook
    depends_on:
      - api
    restart: always

volumes:
  postgres_data:
