"""Add content to KnowledgeDocument

Revision ID: 0999f052d238
Revises: 22624e88d46d
Create Date: 2026-02-17 01:44:41.582206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0999f052d238'
down_revision: Union[str, None] = '22624e88d46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_documents', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_documents', 'content')
    # ### end Alembic commands ###
