"""Add summary

Revision ID: 22624e88d46d
Revises: 716ddc58fdf8
Create Date: 2026-02-16 21:04:09.997618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22624e88d46d'
down_revision: Union[str, None] = '716ddc58fdf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('contacts', sa.Column('last_chat_date', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'last_chat_date')
    op.drop_column('contacts', 'summary')
    # ### end Alembic commands ###
