"""Add_AI_Groq_Config

Revision ID: 716ddc58fdf8
Revises: 97fdbc4857e1
Create Date: 2026-02-16 19:13:11.955812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '716ddc58fdf8'
down_revision: Union[str, None] = '97fdbc4857e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_settings', sa.Column('groq_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('whatsapp_sessions', sa.Column('system_prompt', sa.Text(), nullable=True))
    op.add_column('whatsapp_sessions', sa.Column('ai_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='openai'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_sessions', 'ai_provider')
    op.drop_column('whatsapp_sessions', 'system_prompt')
    op.drop_column('company_settings', 'groq_api_key')
    # ### end Alembic commands ###
