"""Init SaaS BAPE

Revision ID: 97fdbc4857e1
Revises: 
Create Date: 2026-02-16 13:01:47.456042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97fdbc4857e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create Enums manually using robust SQL handling
    # UserRole
    op.execute("""
    DO $$ BEGIN
        CREATE TYPE userrole AS ENUM ('SUPERADMIN', 'ADMIN', 'AGENT');
    EXCEPTION
        WHEN duplicate_object THEN null;
    END $$;
    """)
    
    # MessageRole
    op.execute("""
    DO $$ BEGIN
        CREATE TYPE messagerole AS ENUM ('USER', 'ASSISTANT', 'SYSTEM');
    EXCEPTION
        WHEN duplicate_object THEN null;
    END $$;
    """)
    
    # MessageType
    op.execute("""
    DO $$ BEGIN
        CREATE TYPE messagetype AS ENUM ('TEXT', 'IMAGE', 'AUDIO', 'VIDEO', 'DOCUMENT');
    EXCEPTION
        WHEN duplicate_object THEN null;
    END $$;
    """)

    # Now define tables
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('limits', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('openai_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telegram_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_phone'), 'contacts', ['phone'], unique=False)
    op.create_table('whatsapp_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_sessions_session_name'), 'whatsapp_sessions', ['session_name'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('role', postgresql.ENUM('USER', 'ASSISTANT', 'SYSTEM', name='messagerole', create_type=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('type', postgresql.ENUM('TEXT', 'IMAGE', 'AUDIO', 'VIDEO', 'DOCUMENT', name='messagetype', create_type=False), nullable=False),
    sa.Column('media_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('product_categories', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_product_categories_id'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_name'), table_name='product_categories')
    op.create_index(op.f('ix_product_categories_name'), 'product_categories', ['name'], unique=False)
    op.create_foreign_key(None, 'product_categories', 'companies', ['company_id'], ['id'])
    op.drop_column('product_categories', 'created_at')
    op.add_column('products', sa.Column('company_id', sa.Integer(), nullable=True))
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.create_foreign_key(None, 'products', 'companies', ['company_id'], ['id'])
    op.drop_column('products', 'long_description')
    op.drop_column('products', 'short_description')
    op.add_column('service_categories', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_service_categories_id'), table_name='service_categories')
    op.drop_index(op.f('ix_service_categories_name'), table_name='service_categories')
    op.create_index(op.f('ix_service_categories_name'), 'service_categories', ['name'], unique=False)
    op.create_foreign_key(None, 'service_categories', 'companies', ['company_id'], ['id'])
    op.drop_column('service_categories', 'created_at')
    op.add_column('services', sa.Column('company_id', sa.Integer(), nullable=True))
    op.alter_column('services', 'price',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('services', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.create_foreign_key(None, 'services', 'companies', ['company_id'], ['id'])
    op.drop_column('services', 'long_description')
    op.drop_column('services', 'short_description')
    op.add_column('users', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('role', postgresql.ENUM('SUPERADMIN', 'ADMIN', 'AGENT', name='userrole', create_type=False), nullable=False, server_default='SUPERADMIN'))
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'company_id')
    op.drop_column('users', 'role')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.add_column('services', sa.Column('short_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('services', sa.Column('long_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.alter_column('services', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('services', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('services', 'company_id')
    op.add_column('service_categories', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'service_categories', type_='foreignkey')
    op.drop_index(op.f('ix_service_categories_name'), table_name='service_categories')
    op.create_index(op.f('ix_service_categories_name'), 'service_categories', ['name'], unique=True)
    op.create_index(op.f('ix_service_categories_id'), 'service_categories', ['id'], unique=False)
    op.drop_column('service_categories', 'company_id')
    op.add_column('products', sa.Column('short_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('long_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.alter_column('products', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('products', 'company_id')
    op.add_column('product_categories', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product_categories', type_='foreignkey')
    op.drop_index(op.f('ix_product_categories_name'), table_name='product_categories')
    op.create_index(op.f('ix_product_categories_name'), 'product_categories', ['name'], unique=True)
    op.create_index(op.f('ix_product_categories_id'), 'product_categories', ['id'], unique=False)
    op.drop_column('product_categories', 'company_id')
    op.drop_table('messages')
    op.drop_index(op.f('ix_whatsapp_sessions_session_name'), table_name='whatsapp_sessions')
    op.drop_table('whatsapp_sessions')
    op.drop_index(op.f('ix_contacts_phone'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('company_settings')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_table('plans')
    
    # Drop Enums manually if needed or leave them
    # bind = op.get_bind()
    # sa.Enum(name='userrole').drop(bind, checkfirst=True)
    # ...
    # ### end Alembic commands ###
