"""Add AppointmentConfig

Revision ID: 999d5957bff3
Revises: 7d263b651b57
Create Date: 2026-02-17 14:40:22.795745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999d5957bff3'
down_revision: Union[str, None] = '7d263b651b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointmentconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('slot_duration', sa.Integer(), nullable=False),
    sa.Column('gap_between_slots', sa.Integer(), nullable=False),
    sa.Column('working_hours', sa.JSON(), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('google_calendar_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('google_access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('google_refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('mandatory_fields', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('document_chunks', 'content',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_table('appointmentconfig')
    # ### end Alembic commands ###
